version: "3.7"
services:
  mysql_db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network
    environment:
      - MYSQL_DATABASE=datium
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
  
  python_app:
    build: python_app
    restart: always
    secrets:
      - db-password
    networks:
      - backend-network
      - frontend-network

volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  backend-network:
  frontend-network: